
trigger:
 - master 
 
 #Powershell
#Run a powershell script
-task: Powershell@2
inputs: 
  targetType: 'filePath'
  filePath: '/PSScripts/PIMRoles.ps1'
  arguments: 
   - subname: $(subname)
   - testGroup: $(testGroup)
  errorActionPreference: 'stop'