# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: devopspim
  inputs:
    secureFile: 'devopspim.pfx'

- task: PowerShell@2
  inputs:
    filePath: 'PSScripts/PIMRoles.ps1'
    arguments: '-subname $(subname) -testGroup $(testGroup) -appid $(appId) -tenantId $(tenantId) -secret $(secret) -thumb $(thumb)'