
trigger:
 - master 

 variables: 
   subname: $(subname)
   testGroup: $(testGroup)
 
 #Powershell
#Run a powershell script
-task: Powershell@2
inputs: 
  targetType: 'filePath'
  filePath: '/PSScripts/PIMRoles.ps1'
  errorActionPreference: 'stop'